### ISSUE TITLE
Add API endpoint for starting a game

### ISSUE THREAD

**Issue by metalalive** [Game-as-a-Service/Pandemic-Reign-of-Cthulhu#12]
#### Overview
The endpoint is in current [Open API doc](https://game-as-a-service.github.io/Pandemic-Reign-of-Cthulhu/doc/api) :

`/games/{gameId}/start` , `PATCH` method , no request body

The backend service will :
- transition  internal state of game model to `start-playing` , subsequent configuration **will be rejected**, such as switch to different investigator.
- forward the same request body ,  emit `game-start` event with it to all other players
-  response body of the REST endpoint should be empty

I'll modify request body of the REST endpoint to something like :
```json
{"player_id":"xxyy123456"}
```
Since the endpoint needs to know which player triggers the start button

#### Question (Answered / Closed)
what is the effect of the endpoint ? here are 2 options :
- the game starts immediately as soon as **any player** in a game  calls the API endpoint 
- the game starts ONLY after **all players** in a game  call the API endpoint <--  OK

Then both of the options should trigger event to `socket.io` server, which notifies other players the game has started.

- - - - 

c.c. @wingtkw, 
For those still interested with the game dev, please take a look,
feedback or suggestion are welcome.

I am working on this GitHub Issue ,
It is simply creating new endpoint and a use-case class with **empty logic**,
left rest of detail to game domain model.

**Comment by metalalive** [comment]
Ted , is it ok for you to start working on this issue recently ?
Currently Wing should deal with another more important issue --> [the broken frontend CI flow](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/discussions/35) ,
 in order to find other potential fronted code contributors (see #32 for detail)
thanks again.

**Comment by wingtkw** [comment]
It's better for all the players to call the endpoint to at least they are not afk and will join the game

**Comment by metalalive** [comment]
OK , I can take this after #37 ,

**Comment by wingtkw** [comment]
So you will try to use the player ID to find which room game that you should mark it as start
Is that correct?

**Comment by metalalive** [comment]
Hi, wingtkw

> So you will try to use the player ID to find which room game that you should mark it as start

Yes , due to the fact custom data like player ID cannot be embedded in authentication token (JWT) provided by the Lobby Platform.
Another REST endpoint  `/games/{gameId}/investigator`  in the [API doc](https://game-as-a-service.github.io/Pandemic-Reign-of-Cthulhu/doc/api/#/init/patch_games__gameId__investigator) also has similar format in its request body.

**Comment by metalalive** [comment]
Thanks wingtkw for the approval.
Anyone who needs to modify the endpoint can reopen  this issue
