### ISSUE TITLE
Host Open API documentation in any static site

### ISSUE THREAD

**Issue by metalalive** [Game-as-a-Service/Pandemic-Reign-of-Cthulhu#2]
Host Open API documentation in any static site like Github,

Currently I know how to enable Github Page

I will learn how to set up OpenAPI spec with Swagger UI then host them in the Github Page when I have time.

Reference: [Creating a GitHub Pages site](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site)

**Comment by metalalive** [comment]
@wingtkw would you like to learn to :
-  generate static web pages from the Open API spec , using [Swagger UI](https://github.com/swagger-api/swagger-ui)
-  and host it using [GItHub Page](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site) ?

please leave your comment at here, if you are too busy to finish the task, maybe I can help to set up ?

By T.H.

**Comment by KalpasWang** [comment]
我可以嘗試看看，可以提供一些 reference 嗎？

**Comment by sandytang886** [comment]
sure, I would try it on Wednesday

**Comment by metalalive** [comment]
@sandytang886 , @KalpasWang 
Reference: 
- [Creating a GitHub Pages site](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site)
- [Swagger UI](https://github.com/swagger-api/swagger-ui#documentation) , see the installation doc
- [current Open API spec](https://www.notion.so/Endpoint-Specification-OpenAPI-Spec-de3bad08ac6946ed85d23b632d0bc2f7?pvs=4) , maybe it is still in-progress (not containing the endpoints we discussed in the last meeting), please ask @wingtkw again.

**Comment by KalpasWang** [comment]
@metalalive 
is this branch doc/api-ref-site can be used to host swagger ui?

**Comment by sandytang886** [comment]
我在branch push了新的commit ,但還是有點問題，本身測試過應該是可以直接開啟index.html，但開啟的時候就開了readme.md，想問是不是有哪裡的錯漏和有沒有其他問題？

**Comment by sandytang886** [comment]
ok i fixed . now the api link should be : https://game-as-a-service.github.io/Pandemic-Reign-of-Cthulhu/doc/api/

**Comment by metalalive** [comment]
Sandy I think you are ready to merge the  branch `doc/api-ref-site`,
please create Pull Request and ask Kalpas Wang or Wing to review and then approve.

**Comment by metalalive** [comment]
@sandytang886 ,  since you've made small change in the codebase,
you can merge the change / the code in the branch `doc/api-ref-site`, to the `main` branch.
Please create a Pull Request, and set somebody as a reviewer (I can help to review your PR), 
then approve the PR whenever the PR is approved, 
thanks
