### ISSUE TITLE
change difficulty before game start

### ISSUE THREAD

**Issue by metalalive** [Game-as-a-Service/Pandemic-Reign-of-Cthulhu#27]
For the endpoint `/games/{gameId}/difficulty` , `PATCH` method, in [the API doc](https://game-as-a-service.github.io/Pandemic-Reign-of-Cthulhu/doc/api)

@wingtkw would you like to take this task and practice to build the endpoint with FastAPI ?
I dunno how much you understand the python code Ted and I have done so far.

**Comment by wingtkw** [comment]
Sure I can take that

**Comment by wingtkw** [comment]
Fyi, I have started writing the code, and will try to clear it tmr as I get half day off

**Comment by metalalive** [comment]
Sounds good,
For any implementation questions you can leave comments in GitHub Discusion,
And don't forget to review the [PR28](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/pull/28) for me , thanks again

**Comment by wingtkw** [comment]
I have pushed the code just now in feature/update-difficulty branch
you may take a look of it, thanks
@metalalive @teds-lin

**Comment by metalalive** [comment]
Hey, I left my comments directly to [your latest commit](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/commit/e104474a9b565df17352300e2d3b5f984579a3e1) , please take a look.

Also, I found that the branch you created `feature/update-difficulty` is 1 commit ahead, 4 commits behind `main` branch, 
that will make GitHub **unable to automatically merge your branch**, 

It is recommended that :
- you keep your original code change in another branch of your local codebase. 
- then download from the main branch of the remote codebase, using `git pull`, to your local codebase.
  - the latest version of the class `app.domain.GameError` will make your work easier (see [the code in main branch](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/blob/main/backend/app/domain/game.py) ), so you don't need to specify string detail when creating `GameError` instance.
-  finally move your previous code change to your up-to-date local codebase.

**Comment by metalalive** [comment]
Hey, WIng, I reopened the issue #10 and will modify the code in the function ` CreateGameUseCase.execute(...)` (plz read my [latest comment](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/issues/10#issuecomment-1810582510)) ,

but I prefer to merge your code in this GItHub Issue into `main` branch before I  start doing that, please let us know if you are stuck at somewhere in the code or git conflict to resolve, thanks.

**Comment by wingtkw** [comment]
Ok
Let me revise it tonight

**Comment by wingtkw** [comment]
@metalalive revised & committed
feel free to review it, thanks

**Comment by wingtkw** [comment]
pushed the new commit again

**Comment by metalalive** [comment]
[PR33](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/pull/33) approved , don't forget the final step -- go to the PR page then click the button `merge pull request` .
