### ISSUE TITLE
Python Backend Environment Initial Setup

### ISSUE THREAD

**Issue by metalalive** [Game-as-a-Service/Pandemic-Reign-of-Cthulhu#3]
Package management : poetry
Packages to install : fastapi, starlette, uvicorn, pytest
Linter : Ruff
code formatter : Black

See [Notion discussion](https://www.notion.so/Dev-env-setup-for-Python-backend-d8e04350759c4e03a8e29f31276838e4?pvs=4)

c.c. : @teds-lin ,  @wingtkw

**Comment by metalalive** [comment]
[poetry](https://python-poetry.org/docs/) is installed in my env from the official github repository . Here is my command
```shell
curl -sSL https://install.python-poetry.org > /PROJECT_HOME/backend/poetry-install.py

POETRY_HOME=${PWD}/env   /PATH/TO/MY/Python-3.9.6/python  \
      /PROJECT_HOME/backend/poetry-install.py  \
     --git https://github.com/python-poetry/poetry.git@master
```

In my case, the installation script will report errors without the `--git` option  (a.k.a the default suggested flow)
I would come back to this error in the future when it is necessary.

```shell
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
   certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
```

**Comment by metalalive** [comment]
Currently there is PR #5 to review and merge,
the env setup does not include continuous integration (CI) flow yet,
I will start another branch for CI and GitHub Action.

**Comment by metalalive** [comment]
PR #5 merged, will learn how to set up CI flow with GitHub Action.
teds would you like to do this ?
or I can take responsibility of the task.

**Comment by teds-lin** [comment]
好哦，我會抽空處理

Ham ***@***.***> 於 2023年10月21日 週六 23:20 寫道：

**Comment by metalalive** [comment]
if you have any question about GitHub Action please let me know ,
 I will also create  new temporary branch to try the flow
 (but it won't merge to the `main` branch, it is just for expanding my knowledge).
