### ISSUE TITLE
Socket.io API endpoint for players of a game to start real-time communication

### ISSUE THREAD

**Issue by metalalive** [Game-as-a-Service/Pandemic-Reign-of-Cthulhu#37]
### API endpoint to `socket.io` server
- `localhost:8082` ,  path `/` ,GET method, no request body
- Identity authentication and authorization (e.g. [verify [JWT](https://jwt.io/) signature) will be postponed
  - we can do that when we start JWT implementation for HTTP RESTful server

#### Client (Player)
Possible [events namespace to emit](https://socket.io/docs/v4/emitting-events/) (or [topics](https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern#Message_filtering) to publish)
- `/game/{game-id}/join` **<-- Not sure whether this is good design option**
  - For later comer who attempts to join a game which hasn't been started yet
  - Possible arguments : e.g. `player-id = abc999xyz`
  - Note we have not decided which binary format to apply to event message, but it is not JSON for sure.

- `/game/{game-id}/chat`
  - For player chatting with other players of the same existing game
  - Possible arguments : e.g. `player-id = abg007xyz`, `chat-message = Hello World`

Possible events namespace to receive (topics to subscribe)
- `/game/{game-id}/config/difficulty`
  - refresh game difficulty
  - Possible arguments : e.g. `level = standard`,
- `/game/{game-id}/config/investigators`
  - refresh the config, shows which player successfully selected which investigator
  - Possible arguments : e.g. `player-id = SamuraiBuck`, `investigator =  magician`

There should be **many more topics to subscribe** for each player
- especially when the game started , each player completes any action or draw any card in his / her turn.
- for now , I simply list a few we can try to implement in the beginning.

#### HTTP RESTful server
Possible events namespace to emit (or topics to publish)
- `/game/{game-id}/config/difficulty`
- `/game/{game-id}/config/investigators`

Possible events namespace to receive (topics to subscribe)
- None

### Question
- event namespace `/game/{game-id}/join` , <-- is this good design option ?
  - what about adding new REST endpoint `/game/{game-id}/join` ? to let the HTTP RESTful server know one more person would like to join , then re-use `Game.add_player()` in backend code.

### TODO
- implement minimal working socket.io server
- infra setup (`python-socketio` and Kafka)

### Reference
See previous discussion #29

@wingtkw  @teds-lin  , plz take a look at this,
feedback or suggestion are welcome , thanks.

**Comment by teds-lin** [comment]
> - /game/{game-id}/join <-- Not sure whether this is good design option
>   - For later comer who attempts to join a game which hasn't been started yet

設計方針是只與GaaS大平台串接還是會有考慮其他遊戲登錄平台？
這是指之後有其他玩家也想要加入遊戲房間，所以一同遊玩人數會變更的情境嗎？
如果是GaaS大平台串接，
因為是等大平台那邊玩家都組好隊，
才會送過來，當送過來後，
GaaS也沒辦法在新增玩家進來，
所以我認為先不考慮這個功能

> - `/game/{game-id}/chat`

不是很懂，看前面一條我以為這邊都是在討論REST endpoint?
可是下面解釋說是"player chatting with other players" 所以是在講`socket.io`?
我不認為玩家聊天API需要在REST endpoint也建置對應的，徒增複雜度
socket.io的話 namespace [官網圖](https://socket.io/docs/v4/server-api/#namespace)有點難懂
其實就是像這篇[文章](https://medium.com/@ipenywis/node-js-socket-io-namespaces-rooms-and-connections-02-14e84dbdba46)介紹的
Client可以建立很多socket連線到不同的[namespace](https://socket.io/docs/v4/namespaces/)，每個[namespace](https://socket.io/docs/v4/namespaces/)又可以分很多[room](https://socket.io/docs/v4/rooms/)

在我們遊戲這個case，
我認為很簡單的用原本預設的"/"就好，
然後共同遊戲的玩家都在同一個`game-id`的room內


> There should be **many more topics to subscribe** for each player

是在講Kafka?
如果是在講socket.io的event namespace
和game相關的可能是`game_state`或者直接叫`game`之類的也可以
與玩家聊天相關的，就`chat`之類的名稱
只要兩個就可以明確分隔遊戲狀態更新與聊天訊息

加上之前討論我說
> 考慮只傳送差異更新而不是完整遊戲狀態

為了舉例方便，我用JSON示範
具體程式碼片段可能會像
```python
# 已從Kafka接收到新的難度等級
new_difficulty_level = STANDARD

# 發布遊戲狀態更新到前端
sio.emit(
    'game', 
    {'event': CHANGE_DIFFICULTY_STATE,
      'difficulty': new_difficulty_level},
    to=game_id
)
```

**Comment by metalalive** [comment]
Hi, Ted, 我先回答部分問題

> 設計方針是只與GaaS大平台串接還是會有考慮其他遊戲登錄平台？

只考慮 GaaS 大平台

> 這是指之後有其他玩家也想要加入遊戲房間，所以一同遊玩人數會變更的情境嗎？
如果是GaaS大平台串接，
因為是等大平台那邊玩家都組好隊，
才會送過來，當送過來後，
GaaS也沒辦法在新增玩家進來，
所以我認為先不考慮這個功能

是的, 目前的 GaaS 大平台 無法增加更多玩家到 已存在的遊戲房間
我以為這部分是由每個遊戲應用程式處理, 
所以我最初的問題是 : 
- 我們是否應該添加  REST endpoint `/game/{game-id}/join` , 讓一些稍後過來的玩家 能進入房間 ?
- 或者，讓玩家先連接到`socket.io` server , 然後 subscribe event , with the namespace `/game/{game-id}/join` ?

但ok , 這也不是關鍵功能，可以先不考慮

---

>  > -   /game/{game-id}/chat
>
> 不是很懂，看前面一條我以為是在討論REST endpoint?
可是下面解釋說是"player chatting with other players" 所以是在講socket.io?

這不是 `REST endpoint`, 這是 `event namespace`  , [這是官方文件中的範例](https://socket.io/docs/v4/namespaces/#custom-namespaces)
- 假設 玩家 (client) 透過 `https://localhost:8082/` 連接到 `socket.io` server
- 連線建立後, 玩家 可以決定監聽哪個 event , with custom namespace such as :
  -  `/game/{game-id}/chat` , 接收同一遊戲房間 其他玩家的訊息
  - `/game/{game-id}/config/investigators` 如果任何玩家更改了 investigator ，這個事件應該反映到同一房間的其他玩家
  - `/game/{game-id}/config/difficulty` ,  如果任何玩家更改了 difficulty level ，這個事件應該反映到同一房間的其他玩家

所以我最初的comment 是問你們對 namespace 的命名規則有何偏好

---

> 其實就是像這篇[文章](https://medium.com/@ipenywis/node-js-socket-io-namespaces-rooms-and-connections-02-14e84dbdba46)介紹的
Client可以建立很多socket連線到不同的[namespace](https://socket.io/docs/v4/namespaces/)，每個[namespace](https://socket.io/docs/v4/namespaces/)又可以分很多[room](https://socket.io/docs/v4/rooms/)

這個我知道, 我們可能在談論同一件事
- 簡單的 namespace --> `/game`, `/chat` , `/something/else`
- 比較複雜的 namespace --> `/game/{game-id}/chat`  ,   `/game/{game-id}/config/investigators` , `/game/{game-id}/state/card-draw` , 其中 `{game-id}` 是代表遊戲id的動態字串

**Comment by metalalive** [comment]
Hi, Ted , continue to reply rest of the questions 

> 如果是在講socket.io的event namespace
目前我想到兩個設計方案
(1)
 ...... omitted ........
(2)
另外一個設計方案就是
將玩家聊天相關內容獨立出來，event namespace命名就chat之類的名稱
這樣可以明確分隔傳送的是遊戲狀態更新(game)還是聊天訊息(chat)

I prefer the 2nd design option, but I am not sure whether I can set up the namespace with `/game/{game-id}` in the backend app , I will try the library `python-socketio` in my local development environment & reply later with my experiment result .

**Comment by wingtkw** [comment]
想問一下
State card draw 是想用來做甚麽的

**Comment by metalalive** [comment]
> State card draw 是想用來做甚麽的
是回合抽卡完成
誰的回合
還是別的

抱歉，我只是舉個例子, 目前我還沒考慮實作細節
請忽略這個 card draw 

我目前正在做的 socket.io topics
- `/game/{game-id}/chat`  
- `/game/{game-id}/config/investigators`

**Comment by metalalive** [comment]
#### Status update
To everyone following this issue : 

[1]
The [comment](https://github.com/miguelgrinberg/python-socketio/issues/332#issuecomment-523886747) in this `python-socketio` issue describes that `socket.io` client with `http` requires [`aiohttp`](https://github.com/aio-libs/aiohttp) , otherwise there will be timeout exception on the client side.

[2]
the `namespace` in `python-socketio` seems more like a constant than a variable, it might NOT be good practice to generate namespace **dynamically** at runtime. Quote my previous comment :
  > I prefer the 2nd design option, but I am not sure whether I can set up the namespace  such like `/game/{game-id}` in the backend app (where `{game-id}` is a variable) , I will try the library python-socketio in my local development environment & reply later with my experiment result .

After coding with `python-socketio` library, I will give up to do that , instead I'll set `{game-id}` to `room` with each event and namespace .

[3]
I tried [`AsyncClient`](https://python-socketio.readthedocs.io/en/stable/api.html#socketio.AsyncClient) in my test case, the client can register event-handling  callback by class function [`on(...)`](https://python-socketio.readthedocs.io/en/stable/api.html#socketio.AsyncClient.on) , however the handler callback does not seem to provide any argument that represents which client is receiving which message , this makes tests harder to write.

[4]
I will update this comment later and push my commits to the branch [`experiment/backend/socketio`](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/tree/experiment/backend/socketio)  (it is only for experiment purpose) .

**Comment by metalalive** [comment]
TODO : 
- replace print message with logger in `socket.io` server
- for binary payload format , try switching to `FlatBuffers` or `ProtoBuf` (see [previous discussion](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/discussions/29#discussioncomment-7643335))

--- **create PR, merge to main branch** ---

- REST HTTP server sends event for updating   difficulty level of specific game, to `socket.io` server , the socket.io sevrer forwards the events to the players
- REST HTTP server sends event for updating   character selection of specific game, to `socket.io` server .
- experiment with Kafka adapter to `socket.io`

--- **create PR, merge to main branch** ---

**Comment by teds-lin** [comment]
> 通常`event namespace`和上面剛剛提到的`namespace`命名上最大區別就是最前頭會不會加上`/`

我注意到實驗分支 [experiment/backend/socketio](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/tree/experiment/backend/socketio) 實作中
`event namespace` 命名開頭都加上`/`,  例如 `/chat`, ` /init`等
好奇這樣取名原因是？

一些相關討論：
[Custom event naming convention](https://github.com/socketio/socket.io/issues/1571#issuecomment-69520702)
[Is there any name convention for response event in socketIO?](https://stackoverflow.com/questions/67922298/is-there-any-name-convention-for-response-event-in-socketio)

> I am considering to add another API doc at [doc/api](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/tree/main/doc/api) for the socket.io real-time communication,

socket.io 文件通常用 [AsyncAPI ](https://www.asyncapi.com/)撰寫, 但我不確定同樣放在`doc/api`這樣能不能相容, 或者放在`doc/socketio`？
[Pt1](https://www.asyncapi.com/blog/socketio-part1)
[Pt2](https://www.asyncapi.com/blog/socketio-part2)

**Comment by metalalive** [comment]
Hi , Ted
> `event namespace` 命名開頭都加上`/`,  例如 `/chat`, ` /init`等
好奇這樣取名原因是？

Since the naming convention of `socket.io` event really depends on development team, anything here can be changed.
But yes, there is no reason to add extra slash symbol `/` at the beginning of event name, this can also be removed,
current events will be renamed to `chat` , `init`, `deinit`

> socket.io 文件通常用 [AsyncAPI ](https://www.asyncapi.com/)撰寫, 但我不確定同樣放在doc/api這樣能不能相容, 或者放在`doc/socketio`？

It is also OK to place it in the path `doc/socketio` , 
`AsyncAPI` , event-driven architecture API document, thanks, good to know this

**Comment by metalalive** [comment]
Let us focus on section portion of [the TODO list](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/issues/37#issuecomment-1842635038) in this GitHub Issue , discussion / design / implementation approaches are appreciated.

- the REST server emits event on creating new game
- then socket.io server receives the event to know which players should be in which game room.

**Comment by wingtkw** [comment]
Let me review it on 15
Got AL on that day

**Comment by metalalive** [comment]
I'll come back work on this tomorrow (finally)

**Comment by metalalive** [comment]
I am working on the 3rd portion of [the TODO list](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/issues/37#issuecomment-1842635038) in this GitHub Issue , discussion related to the design / implementation are appreciated.

**Comment by metalalive** [comment]
I will work on the 4th (final) portion of [the TODO list](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/issues/37#issuecomment-1842635038) in this GitHub Issue.

I'll try [`FlatBuffers`](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/discussions/29#discussioncomment-7643335) first with `pydantic` and `socket.io` server and see how it goes

Appreciated discussion related to the design / implementation.
c.c. @wingtkw , @KalpasWang , @liamlin1102

**Comment by metalalive** [comment]
Currently close this Issue,
any code / design contributor can reopen it whenever there is new event to add in the real-time communication.

**Comment by KalpasWang** [comment]
@metalalive 
it seems everyone disappear except us, what happened? 🤔
